### ISSUE TITLE
Panic on startup in src/text/fonts.rs

### ISSUE THREAD

**Issue by agraven** [tim-harding/neophyte#11]
Attempting to run neophyte fails with the following panic message
```
thread 'main' panicked at src/text/fonts.rs:100:14:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
After cursory testing this appears to happen on both nightly and stable neovim, both with fonts fully configured via the lua plugin, and with an entirely clean configuration, on both NixOS 23.11 and Ubuntu 23.10.

**Comment by tim-harding** [comment]
@agraven  Thank you for the report. I assume that you most likely used Git to download the repo and built the project manually. If so, the readme now outlines that `git lfs install && git lfs pull` are required to correctly fetch the default fonts that are loaded at startup. Please let me know if that is not the case.
