### ISSUE TITLE
How to run neophyte in Windows and use WSL neovim?

### ISSUE THREAD

**Issue by jla2000** [tim-harding/neophyte#17]
Would it be possible to configure the neovim binary path to allow connecting to a wsl instance and use the neovim installed there?

**Comment by tim-harding** [comment]
The latest commit allows you to do this:
```bash
neophyte -- wsl $SHELL -lc "nvim"
```
Not sure what the exact command will need to be, but this is roughly what Neovide produces with the `--wsl` flag. Could you let me know how that works for you?

**Comment by jla2000** [comment]
Did not work unfortunately:
```
thread 'main' panicked at src\main.rs:50:6:
Failed to start Neovim: Error { kind: NotFound, message: "program not found" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Might be related though due to my own setup, both the shell and neovim itself are installed via nix.

**Comment by tfriedel** [comment]
I tried 
neophyte-windows.exe -- wsl -- nvim
I assume this should work, as "wsl -- nvim" will open nvim inside wsl. 
However I get this error:
ERROR [neophyte::neovim::stdout_thread] Failed to parse an RPC message
