### ISSUE TITLE
Font size ignored

### ISSUE THREAD

**Issue by yashamon** [tim-harding/neophyte#23]
On windows, specifying font size either in init.lua or in the config for neophyte seems to be totally ignored. Always get tiny font about size 10.

**Comment by tim-harding** [comment]
Can you share the config you're using?

**Comment by yashamon** [comment]
I just did neophyte -- nvim -- clean
and then lua opt.guifont = "JetBrains Mono NL:h18"
the latter is installed as the font works in neovide.

**Comment by tim-harding** [comment]
Thanks for the report. It should be working again in the latest commit.
