### ISSUE TITLE
File explorer are not visible

### ISSUE THREAD

**Issue by Jezda1337** [tim-harding/neophyte#8]
Hey, I have an issue with floating file-explorer in my case, nvim-tree. See the video:
The left side is neophyte, and the right side is my tmux alacritty.
Seams inner width is wider then the main  window

[Screencast from 2024-01-12 12-31-59.webm](https://github.com/tim-harding/neophyte/assets/42359294/cb9360f8-3e63-487a-9b55-a339200cc22f)

**Comment by tim-harding** [comment]
I will take a look. Do you have a public dotfiles repo that I could use to reproduce?

**Comment by Jezda1337** [comment]
> I will take a look. Do you have a public dotfiles repo that I could use to reproduce?

Sure, [link](https://github.com/Jezda1337/.dotfiles/tree/main/.config/nvim)

**Comment by tim-harding** [comment]
I should be working on `main` now. The default terminal GUI repositions out-of-bounds floats to be visible, which I was correcting for when floats were too far left or up but not when they were too far down or right. It seems that the default GUI also fixes the size of bordered floats, which add two extra cells to the sides. For now, you can use `height = vim.o.lines - 2` to avoid the float overflowing.

**Comment by Jezda1337** [comment]
Where should I use this `height = vim.o.lines - 2`. Bdw I get new error: here is the SS
![Screenshot from 2024-01-14 18-20-40](https://github.com/tim-harding/neophyte/assets/42359294/28118465-cd4e-415a-95f9-5bf683155619)

**Comment by tim-harding** [comment]
You would put it in place of this:
https://github.com/Jezda1337/.dotfiles/blob/7524ec9d8d8c3a22df1e8ce3399361b19396ad39/.config/nvim/lua/plugins/nvim-tree.lua#L26C29-L26C29
The tag should be up now. I'm new to tags and forgot I have to push them specifically.

**Comment by Jezda1337** [comment]
I have another issue, should I open new issue for this one? 
![Screenshot from 2024-01-14 19-23-42](https://github.com/tim-harding/neophyte/assets/42359294/9f3b6e8f-f276-4d74-b425-dacded34f9a7)

**Comment by tim-harding** [comment]
That does look worth another issue. I really appreciate the reports. GPU programming is new territory for me and it's difficult to predict what sort of compatibility issues or bugs folks will run into.
